<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::group(['namespace'=>'App\Http\Controllers\Auth','prefix'=>'login','middleware'=>'guest:admin'],function (){
Route::get('/','loginController@login')->name('login');
Route::post('/checkup','loginController@checkup')->name('checkup');
});

Route::group(['middleware'=>'auth:admin','namespace'=>'App\Http\Controllers'],function (){
    Route::get('/','indexController@index')->name('index');
    Route::get('/logout','Auth\loginController@logout')->name('logout');
Route::group(['namespace'=>'Admin','prefix'=>'GeneralSettings'],function(){
    Route::get('/','general_settingsController@index')->name('general_settings_view');
    Route::post('/Edit_settings/{id?}','general_settingsController@edit')->name('settings_edit');
    Route::get('/Edit/{slug?}','general_settingsController@edit_view')->name('edit_view');
    Route::post('/EditRules/{id?}','general_settingsController@edit_rules')->name('settings_edit_rules');
});
    Route::group(['namespace'=>'Admin','prefix'=>'Finance_Calender'],function(){
        Route::get('/','finance_calenderController@index')->name('finance_calender');
//        Route::get('/Months','finance_calenderController@MonthsIndex')->name('Months');
        Route::get('/add','finance_calenderController@add')->name('finance_calender_add');
        Route::post('/addDone','finance_calenderController@addDone')->name('finance_calender_addDone');
        Route::get('/Edit/{slug?}','finance_calenderController@edit')->name('finance_calender_edit');
        Route::post('/EditDone/{id?}','finance_calenderController@editDone')->name('finance_calender_editDone');
        Route::get('/Is_Open/{id?}','finance_calenderController@openOr')->name('finance_calender_open');
        Route::get('/Delete/{id?}','finance_calenderController@delete')->name('finance_calender_dle');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Finance_Cel_Periods'],function(){
        Route::get('/{slug?}','finance_cel_periodsController@index')->name('finance_cel_periods');
        Route::get('/add','finance_cel_periodsController@add')->name('finance_cel_periods_add');
        Route::get('/addDone','finance_cel_periodsController@addDone')->name('finance_cel_periods_addDone');
        Route::get('/Edit/{slug?}','finance_cel_periodsController@edit')->name('finance_cel_periods_edit');
        Route::post('/EditDone/{id?}','finance_cel_periodsController@editDone')->name('finance_cel_periods_editDone');
        Route::post('/EditRules/{id?}','finance_cel_periodsController@openOr')->name('finance_cel_periods_open');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Branches'],function(){
        Route::get('/','branchesController@index')->name('branches');
        Route::get('/add','branchesController@add')->name('branches_add');
        Route::post('/addDone','branchesController@addDone')->name('branches_addDone');
        Route::get('/Edit/{slug?}','branchesController@edit')->name('branches_edit');
        Route::post('/EditDone/{id?}','branchesController@editDone')->name('branches_editDone');
        Route::get('/Active/{id?}','branchesController@active')->name('branches_active');
        Route::get('/Delete/{id?}','branchesController@delete')->name('branches_delete');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Shifts'],function(){
        Route::get('/','shifts_typeController@index')->name('shifts');
        Route::get('/add','shifts_typeController@add')->name('shifts_add');
        Route::post('/addDone','shifts_typeController@addDone')->name('shifts_addDone');
        Route::get('/Edit/{slug?}','shifts_typeController@edit')->name('shifts_edit');
        Route::post('/EditDone/{id?}','shifts_typeController@editDone')->name('shifts_editDone');
        Route::get('/Active/{id?}','shifts_typeController@active')->name('shifts_active');
        Route::get('/Delete/{id?}','shifts_typeController@delete')->name('shifts_delete');
        Route::post('/ajaxSearch','shifts_typeController@ajaxSearch')->name('ajaxSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Departments'],function(){
        Route::get('/','departmentController@index')->name('departments');
        Route::get('/add','departmentController@add')->name('departments_add');
        Route::post('/addDone','departmentController@addDone')->name('departments_addDone');
        Route::get('/Edit/{slug?}','departmentController@edit')->name('departments_edit');
        Route::post('/EditDone/{id?}','departmentController@editDone')->name('departments_editDone');
        Route::get('/Active/{id?}','departmentController@active')->name('departments_active');
        Route::get('/Delete/{id?}','departmentController@delete')->name('departments_delete');
        Route::post('/ajaxSearch','departmentController@departments_Search')->name('departments_Search');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Job_Categories'],function(){
        Route::get('/','job_categorieController@index')->name('job_categories');
        Route::get('/add','job_categorieController@add')->name('job_categories_add');
        Route::post('/addDone','job_categorieController@addDone')->name('job_categories_addDone');
        Route::get('/Edit/{slug?}','job_categorieController@edit')->name('job_categories_edit');
        Route::post('/EditDone/{id?}','job_categorieController@editDone')->name('job_categories_editDone');
        Route::get('/Active/{id?}','job_categorieController@active')->name('job_categories_active');
        Route::get('/Delete/{id?}','job_categorieController@delete')->name('job_categories_delete');
        Route::post('/ajaxSearch','job_categorieController@ajaxSearch')->name('job_categoriesSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Qualifications_types'],function(){
        Route::get('/','qualif_typeController@index')->name('qualif_types');
        Route::get('/add','qualif_typeController@add')->name('qualif_types_add');
        Route::post('/addDone','qualif_typeController@addDone')->name('qualif_types_addDone');
        Route::get('/Edit/{slug?}','qualif_typeController@edit')->name('qualif_types_edit');
        Route::post('/EditDone/{id?}','qualif_typeController@editDone')->name('qualif_types_editDone');
        Route::get('/Active/{id?}','qualif_typeController@active')->name('qualif_types_active');
        Route::get('/Delete/{id?}','qualif_typeController@delete')->name('qualif_types_delete');
        Route::post('/ajaxSearch','qualif_typeController@qualif_typesSearch')->name('qualif_typesSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Qualifications'],function(){
        Route::get('/','qualificationcontroller@index')->name('qualifications');
        Route::get('/add','qualificationcontroller@add')->name('qualifications_add');
        Route::post('/addDone','qualificationcontroller@addDone')->name('qualifications_addDone');
        Route::get('/Edit/{slug?}','qualificationcontroller@edit')->name('qualifications_edit');
        Route::post('/EditDone/{id?}','qualificationcontroller@editDone')->name('qualifications_editDone');
        Route::get('/Active/{id?}','qualificationcontroller@active')->name('qualifications_active');
        Route::get('/Delete/{id?}','qualificationcontroller@delete')->name('qualifications_delete');
        Route::post('/ajaxSearch','qualificationcontroller@qualificationsSearch')->name('qualificationsSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Occasions'],function(){
        Route::get('/','occasionscontroller@index')->name('occasions');
        Route::get('/add','occasionscontroller@add')->name('occasions_add');
        Route::post('/addDone','occasionscontroller@addDone')->name('occasions_addDone');
        Route::get('/Edit/{slug?}','occasionscontroller@edit')->name('occasions_edit');
        Route::post('/EditDone/{id?}','occasionscontroller@editDone')->name('occasions_editDone');
        Route::get('/Active/{id?}','occasionscontroller@active')->name('occasions_active');
        Route::get('/Delete/{id?}','occasionscontroller@delete')->name('occasions_delete');
        Route::post('/ajaxSearch','occasionscontroller@occasionsSearch')->name('occasionsSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Resignations'],function(){
        Route::get('/','resignationscontroller@index')->name('resignations');
        Route::get('/add','resignationscontroller@add')->name('resignations_add');
        Route::post('/addDone','resignationscontroller@addDone')->name('resignations_addDone');
        Route::get('/Edit/{slug?}','resignationscontroller@edit')->name('resignations_edit');
        Route::post('/EditDone/{id?}','resignationscontroller@editDone')->name('resignations_editDone');
        Route::get('/Active/{id?}','resignationscontroller@active')->name('resignations_active');
        Route::get('/Delete/{id?}','resignationscontroller@delete')->name('resignations_delete');
        Route::post('/ajaxSearch','resignationscontroller@resignationsSearch')->name('resignationsSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Nationalitys'],function(){
        Route::get('/','nationalityscontroller@index')->name('nationalitys');
        Route::get('/add','nationalityscontroller@add')->name('nationalitys_add');
        Route::post('/addDone','nationalityscontroller@addDone')->name('nationalitys_addDone');
        Route::get('/Edit/{slug?}','nationalityscontroller@edit')->name('nationalitys_edit');
        Route::post('/EditDone/{id?}','nationalityscontroller@editDone')->name('nationalitys_editDone');
        Route::get('/Active/{id?}','nationalityscontroller@active')->name('nationalitys_active');
        Route::get('/Delete/{id?}','nationalityscontroller@delete')->name('nationalitys_delete');
        Route::post('/ajaxSearch','nationalityscontroller@nationalitysSearch')->name('nationalitysSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Religions'],function(){
        Route::get('/','religionscontroller@index')->name('religions');
        Route::get('/add','religionscontroller@add')->name('religions_add');
        Route::post('/addDone','religionscontroller@addDone')->name('religions_addDone');
        Route::get('/Edit/{slug?}','religionscontroller@edit')->name('religions_edit');
        Route::post('/EditDone/{id?}','religionscontroller@editDone')->name('religions_editDone');
        Route::get('/Active/{id?}','religionscontroller@active')->name('religions_active');
        Route::get('/Delete/{id?}','religionscontroller@delete')->name('religions_delete');
        Route::post('/ajaxSearch','religionscontroller@religionsSearch')->name('religionsSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Blood_types'],function(){
        Route::get('/','blood_typescontroller@index')->name('blood_types');
        Route::get('/add','blood_typescontroller@add')->name('blood_types_add');
        Route::post('/addDone','blood_typescontroller@addDone')->name('blood_types_addDone');
        Route::get('/Edit/{slug?}','blood_typescontroller@edit')->name('blood_types_edit');
        Route::post('/EditDone/{id?}','blood_typescontroller@editDone')->name('blood_types_editDone');
        Route::get('/Active/{id?}','blood_typescontroller@active')->name('blood_types_active');
        Route::get('/Delete/{id?}','blood_typescontroller@delete')->name('blood_types_delete');
        Route::post('/ajaxSearch','blood_typescontroller@blood_typesSearch')->name('blood_typesSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Marital_status'],function(){
        Route::get('/','marital_statuscontroller@index')->name('marital_status');
        Route::get('/add','marital_statuscontroller@add')->name('marital_status_add');
        Route::post('/addDone','marital_statuscontroller@addDone')->name('marital_status_addDone');
        Route::get('/Edit/{slug?}','marital_statuscontroller@edit')->name('marital_status_edit');
        Route::post('/EditDone/{id?}','marital_statuscontroller@editDone')->name('marital_status_editDone');
        Route::get('/Active/{id?}','marital_statuscontroller@active')->name('marital_status_active');
        Route::get('/Delete/{id?}','marital_statuscontroller@delete')->name('marital_status_delete');
        Route::post('/ajaxSearch','marital_statuscontroller@marital_statusSearch')->name('marital_statusSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Military_services'],function(){
        Route::get('/','military_servicescontroller@index')->name('military_services');
        Route::get('/add','military_servicescontroller@add')->name('military_services_add');
        Route::post('/addDone','military_servicescontroller@addDone')->name('military_services_addDone');
        Route::get('/Edit/{slug?}','military_servicescontroller@edit')->name('military_services_edit');
        Route::post('/EditDone/{id?}','military_servicescontroller@editDone')->name('military_services_editDone');
        Route::get('/Active/{id?}','military_servicescontroller@active')->name('military_services_active');
        Route::get('/Delete/{id?}','military_servicescontroller@delete')->name('military_services_delete');
        Route::post('/ajaxSearch','military_servicescontroller@military_servicesSearch')->name('military_servicesSearch');
    });

//    driving_licenses
//    graduation_estimates
//    countrys
//    governorates
//    centers
//    languages

    Route::group(['namespace'=>'Admin','prefix'=>'Driving_licenses'],function(){
        Route::get('/','driving_licensescontroller@index')->name('driving_licenses');
        Route::get('/add','driving_licensescontroller@add')->name('driving_licenses_add');
        Route::post('/addDone','driving_licensescontroller@addDone')->name('driving_licenses_addDone');
        Route::get('/Edit/{slug?}','driving_licensescontroller@edit')->name('driving_licenses_edit');
        Route::post('/EditDone/{id?}','driving_licensescontroller@editDone')->name('driving_licenses_editDone');
        Route::get('/Active/{id?}','driving_licensescontroller@active')->name('driving_licenses_active');
        Route::get('/Delete/{id?}','driving_licensescontroller@delete')->name('driving_licenses_delete');
        Route::post('/ajaxSearch','driving_licensescontroller@driving_licensesSearch')->name('driving_licensesSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Graduation_estimates'],function(){
        Route::get('/','graduation_estimatescontroller@index')->name('graduation_estimates');
        Route::get('/add','graduation_estimatescontroller@add')->name('graduation_estimates_add');
        Route::post('/addDone','graduation_estimatescontroller@addDone')->name('graduation_estimates_addDone');
        Route::get('/Edit/{slug?}','graduation_estimatescontroller@edit')->name('graduation_estimates_edit');
        Route::post('/EditDone/{id?}','graduation_estimatescontroller@editDone')->name('graduation_estimates_editDone');
        Route::get('/Active/{id?}','graduation_estimatescontroller@active')->name('graduation_estimates_active');
        Route::get('/Delete/{id?}','graduation_estimatescontroller@delete')->name('graduation_estimates_delete');
        Route::post('/ajaxSearch','graduation_estimatescontroller@graduation_estimatesSearch')->name('graduation_estimatesSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Countrys'],function(){
        Route::get('/','countryscontroller@index')->name('countrys');
        Route::get('/add','countryscontroller@add')->name('countrys_add');
        Route::post('/addDone','countryscontroller@addDone')->name('countrys_addDone');
        Route::get('/Edit/{slug?}','countryscontroller@edit')->name('countrys_edit');
        Route::post('/EditDone/{id?}','countryscontroller@editDone')->name('countrys_editDone');
        Route::get('/Active/{id?}','countryscontroller@active')->name('countrys_active');
        Route::get('/Delete/{id?}','countryscontroller@delete')->name('countrys_delete');
        Route::post('/ajaxSearch','countryscontroller@countrysSearch')->name('countrysSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Governorates'],function(){
        Route::get('/','governoratescontroller@index')->name('governorates');
        Route::get('/add','governoratescontroller@add')->name('governorates_add');
        Route::post('/addDone','governoratescontroller@addDone')->name('governorates_addDone');
        Route::get('/Edit/{slug?}','governoratescontroller@edit')->name('governorates_edit');
        Route::post('/EditDone/{id?}','governoratescontroller@editDone')->name('governorates_editDone');
        Route::get('/Active/{id?}','governoratescontroller@active')->name('governorates_active');
        Route::get('/Delete/{id?}','governoratescontroller@delete')->name('governorates_delete');
        Route::post('/ajaxSearch','governoratescontroller@governoratesSearch')->name('governoratesSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Centers'],function(){
        Route::get('/','centerscontroller@index')->name('centers');
        Route::get('/add','centerscontroller@add')->name('centers_add');
        Route::post('/addDone','centerscontroller@addDone')->name('centers_addDone');
        Route::get('/Edit/{slug?}','centerscontroller@edit')->name('centers_edit');
        Route::post('/EditDone/{id?}','centerscontroller@editDone')->name('centers_editDone');
        Route::get('/Active/{id?}','centerscontroller@active')->name('centers_active');
        Route::get('/Delete/{id?}','centerscontroller@delete')->name('centers_delete');
        Route::post('/ajaxSearch','centerscontroller@centersSearch')->name('centersSearch');
    });
    Route::group(['namespace'=>'Admin','prefix'=>'Languages'],function(){
        Route::get('/','languagescontroller@index')->name('languages');
        Route::get('/add','languagescontroller@add')->name('languages_add');
        Route::post('/addDone','languagescontroller@addDone')->name('languages_addDone');
        Route::get('/Edit/{slug?}','languagescontroller@edit')->name('languages_edit');
        Route::post('/EditDone/{id?}','languagescontroller@editDone')->name('languages_editDone');
        Route::get('/Active/{id?}','languagescontroller@active')->name('languages_active');
        Route::get('/Delete/{id?}','languagescontroller@delete')->name('languages_delete');
        Route::post('/ajaxSearch','languagescontroller@languagesSearch')->name('languagesSearch');
    });
});

